[package]
name = "lru-cache-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
tester-utils = { git = "https://github.com/SystemQuest/tester-utils.git" }
regex = "1.10"

[[bin]]
name = "lru-cache-tester"
path = "src/bin/main.rs"
